# .readthedocs.yaml
# Read the Docs configuration file for nostress
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx documentation build configuration
sphinx:
  configuration: docs/conf.py
  builder: html
  # Enable strict mode to catch documentation issues early
  # Our configuration suppresses non-critical warnings
  fail_on_warning: true

# Python environment configuration
# Note: We primarily use uv for dependency management, but this provides
# fallback compatibility and ensures RTD can understand our dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Format configuration
formats:
  - htmlzip
  - pdf
  - epub

# Search configuration
search:
  ranking:
    api-reference.html: 1
    cli-reference.html: 2
    quickstart.html: 3
    installation.html: 4
